### PR TITLE
Dx 37

### PR DESCRIPTION
**Pull request by jmulford-bw**
Make sure you've checked off all these things before submitting:

- [ ] This pull request contains 100% test coverage.
- [ ] This pull request is completely documented. All available fields are listed in the docs with description.
- [ ] Each public facing function should include at least one @example in the jsdoc.
- [ ] Run `npm test` before committing.

### CODE REVIEW

**Comment by jmulford-bw** [comment]
Integration test confirmed functionality is still there. All unit tests pass

**Comment by jmulford-bw** [comment]
Another comment, this is a semvar major update since Node V4 is no longer supported

**Comment by Aubron** [comment]
Supported versions on the readme starts by saying that versions > 0.10.0 is supported, we should clarify/correct that.

**Comment by jmulford-bw** [comment]
> Supported versions on the readme starts by saying that versions > 0.10.0 is supported, we should clarify/correct that.

Fixed

**Comment by Aubron** [comment]
Also, as far as I can tell this will still run ./deploy.sh after deployment, which will try and deploy ghpages. I thought we were removing that functionality to decrease the complexity of this security fix?

**Comment by jmulford-bw** [comment]
> Also, as far as I can tell this will still run ./deploy.sh after deployment, which will try and deploy ghpages. I thought we were removing that functionality to decrease the complexity of this security fix?

You're right. Forgot to remove it. FIxed

**Review by Aubron — APPROVED** [review]

**Pull request merged**
