### PR TITLE
Added missing attributes for Transfer of BXML

### PR DESCRIPTION
**Pull request by avbel**

### CODE REVIEW

**Comment by nguyer** [comment]
Thanks for adding this. Looks like the alignment is off, and the build is being rejected by Travis because of this. After you fix it, I'd be happy to merge it.

**Comment by avbel** [comment]
When you publish new release to npm?

**Comment by nguyer** [comment]
I just did :)

**Comment by avbel** [comment]
Thanks :)

2015-09-11 17:06 GMT+03:00, Nicko Guyer notifications@github.com:

**Pull request merged**
