### PR TITLE
Allow download to return a Buffer

### PR DESCRIPTION
**Pull request by marcosc90**
Allow `Media.download` to return a `Buffer` instead of a `binary` encoded string. When working with files, it's better to have the raw buffer, which is faster and uses less memory.

Besides if you want to save the downloaded content to a file or push it to another server, you will have to convert back to buffer

`Buffer.from(response.content, 'binary')`

- [ ] This pull request contains 100% test coverage.
- [X] This pull request is completely documented. All available fields are listed in the docs with description.
- [ ] Each public facing function should include at least one @example in the jsdoc.
- [x] Run `npm test` before committing.

### CODE REVIEW

**Comment by dtolb** [comment]
@marcosc90 Once you can get this green we'll merge. 
Thanks for the contribution!

**Comment by Aubron** [comment]
@marcosc90 - can you resolve the conflicts - We'll get this merged then.

**Comment by marcosc90** [comment]
I'll try to resolve them today or tomorrow when I have a little bit of free time.

**Comment by Aubron** [comment]
Thanks for your contribution - We'll try and put out a new version in the next week or two

**Pull request merged**
