### PR TITLE
Use Node-provided path module for path concatenation

### PR DESCRIPTION
**Pull request by wtcross**
This PR just swaps custom code for using the Node-provided `path` module.

### CODE REVIEW

**Comment by jagoda** [comment]
The `path` module is intended for file system paths and is not appropriate for URLs. Using `path` functions with URLs will break Windows users. `URL.resolve()` should be used for this instead.

**Comment by wtcross** [comment]
`URL.resolve()` is for resolving URLs as an anchor tag would. It doesn't do the same thing as `path.join`.

In any case, good catch on `path.join`. I'll find an alternative.

**Comment by wtcross** [comment]
[URL#resolve](https://nodejs.org/api/url.html#url_url_resolve_from_to)

**Comment by jagoda** [comment]
You are correct that `url.resolve()` does not meet the needs of this code. I misread the original code on the first pass. I did not mean to imply that `path.join()` and `url.resolve()` perform the same function. Thanks for the catch.

**Comment by wtcross** [comment]
I don't think this is worth changing by itself. I'm just going to close the PR.

**Pull request closed without merging**
