### PR TITLE
Add a couple of small things and V2 message attachment fixes

### PR DESCRIPTION
**Pull request by nguyer**
Most importantly, makes it possible to download media received from V2 messages

### CODE REVIEW

**Comment by jmulford-bw** [comment]
@nguyer I'm not against having V2M functionality in here, but we are planning on having new V2M SDKs separate from this

**Comment by nguyer** [comment]
> @nguyer I'm not against having V2M functionality in here, but we are planning on having new V2M SDKs separate from this

That's fine, but we already have V2 code in here. This fixes it 🙂 
I'll push another commit for the formatting things.

**Comment by jmulford-bw** [comment]
> > @nguyer I'm not against having V2M functionality in here, but we are planning on having new V2M SDKs separate from this
> 
> That's fine, but we already have V2 code in here. This fixes it 🙂
> I'll push another commit for the formatting things.

Didn't know we already had V2 code in here. Sounds good, thanks!

**Comment by jmulford-bw** [comment]
@nguyer Doesn't look like your unit tests are passing. What happens when you run "npm test" locally?

**Comment by nguyer** [comment]
It was just formatting stuff. Fixed now.

**Comment by jmulford-bw** [comment]
@nguyer Can you update the package version in package.json to 2.6.6?

**Comment by nguyer** [comment]
@jmulford-bandwidth Sorry, somehow I never saw your request to update the version number. I updated it now.

**Pull request merged**
